### ISSUE TITLE
variables.tf dead link for IAM permissions

### ISSUE THREAD

**Issue by jfurtney** [fortinet/fortigate-terraform-deploy#115]
variables.tf comment under var.IAM profile links to a dead cookbook link.

**Comment by stsimb** [comment]
Correct cookbook link would be https://docs.fortinet.com/document/fortigate-public-cloud/7.2.0/aws-administration-guide/229470/deploying-fortigate-vm-active-passive-ha-aws-between-multiple-zones

But I've found it pretty hard to understand what I need to put in "<AWS IAM ROLE>" string.
A more verbose example with the IAM Role code in terraform instead of a reference to the documentation would be preferable and appreciated.

**Comment by mobilesuitzero** [comment]
thanks for the comment, Have made the change for the url link that still work.
