### ISSUE TITLE
VPN Settings with External Load Balancer (GCP)

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#175]
I've deployed FortiGate using the [ha-dualloadbalancer template](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha-dualloadbalancer), but I'm facing issues when configuring the VPN. Enabling the debug on FortiGate, I cannot see the traffic reaching the instances, and even if I configure in a different port (such as 10443) and enable this port on GCP firewall rule that will be applied to the FortiGate instances in the unstrust VPC I can't reach it.
I'm wondering if there is something different to be able to use VPN with the ha-dualloadbalancer since deploying the [HA template](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha) I can configure without any problems? Here is a screenshot of how I'm configuring the VPN setting and the firewall policy (this config works in the HA template but not in the internal/external one):

![SSL_VPN_Settings](https://github.com/fortinet/fortigate-terraform-deploy/assets/42626863/3706672e-2da2-49ca-b174-2d2d50e063c4)
![policy_VPN-Private-All-Subnets](https://github.com/fortinet/fortigate-terraform-deploy/assets/42626863/77b8231d-43e1-4255-916a-7c2fb592d242)

**Comment by CledersonE** [comment]
I also tried to use the 443 port for the VPN since the external load balancer protocol is configured only TCP (and not all as [UNSPECIFIED](https://cloud.google.com/load-balancing/docs/network/networklb-backend-service#forwarding-rule-protocols)), but still not working.

**Comment by mobilesuitzero** [comment]
Hi @CledersonE 

As GCP's External LB traffic won't NAT the traffic to the private ip of the interface (https://172.16.8.3:10443).   

In this case, you would probably need to have sslvpn listening on loopback interface and then create vip forward the traffic to the loopback interface.

Can take a look at the following URL.
https://community.fortinet.com/t5/FortiGate/Technical-Tip-Unable-to-connect-SSL-VPN-on-Loopback/ta-p/192634
https://community.fortinet.com/t5/FortiGate/Techical-Tip-Access-SSL-VPN-from-Secondary-IP-only/ta-p/248259
https://yurisk.info/2023/03/21/fortigate-vpn-ssl-hardening-guide/#_move_vpn_ssl_listening_interface_to_a_loopback_interface


Otherwise, can just use other ha that doesn't use load balancer setup, and just have public ip associated to the wan interface directly.

Cheers
