### ISSUE TITLE
Inconsistent ip addressing mode for Azure deployments

### ISSUE THREAD

**Issue by agyss** [fortinet/fortigate-terraform-deploy#212]
The configuration for the HA-setup configures the management port ip to be statically assigned (one sample, valid for all HA-setups):
https://github.com/fortinet/fortigate-terraform-deploy/blob/main/azure/7.4/ha-port1-mgmt-crosszone/config-active.conf

For the single instance it is explicitly set to be dynamic:
https://github.com/fortinet/fortigate-terraform-deploy/blob/main/azure/7.4/single/fgtvm.conf

Additionally, the azure documentation clearly points out to specify it as dhcp:
https://learn.microsoft.com/en-us/entra/identity/saas-apps/media/fortigate-ssl-vpn-tutorial/fortigate-deployment-guide-converted#ensure-network-interfaces-are-obtaining-ip-addresses

So I'm wondering why in the examples it is configured to be static? Especially as this will break the fortigate if configured over the UI as follows.

Create new fortigate in Azure, navigate to the interfaces tab, change type from dhcp to static, get locked out.

**Comment by mobilesuitzero** [comment]
Hi agyss,

With HA, it needs to be statically assigned.  Hence, the ip addresses of the ports during the bootstrap are changed to use static instead of using dhcp.

For the stand alone it is kept as dhcp.

And, changing from dhcp to static, then user must enter the route prior to change,otherwise, won't have the default route that it retrieved from dhcp server.


Cheers
